// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlaywrightTestLinuxContainer;

#nullable disable

namespace Core.Migrations
{
    [DbContext(typeof(SiteTimingContext))]
    partial class SiteTimingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PlaywrightTestLinuxContainer.Entities.SiteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FaviconBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScreenshotBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Size")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("PlaywrightTestLinuxContainer.Entities.TimingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<long>("ConnectEnd")
                        .HasColumnType("bigint");

                    b.Property<long>("ConnectStart")
                        .HasColumnType("bigint");

                    b.Property<long>("DOMContentLoadedEventInChrome")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<long>("DomComplete")
                        .HasColumnType("bigint");

                    b.Property<long>("DomContentLoadedEventEnd")
                        .HasColumnType("bigint");

                    b.Property<long>("DomContentLoadedEventStart")
                        .HasColumnType("bigint");

                    b.Property<long>("DomInteractive")
                        .HasColumnType("bigint");

                    b.Property<long>("DomLoading")
                        .HasColumnType("bigint");

                    b.Property<long>("DomainLookupEnd")
                        .HasColumnType("bigint");

                    b.Property<long>("DomainLookupStart")
                        .HasColumnType("bigint");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExceptionStackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FetchStart")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsSuccessfull")
                        .HasColumnType("bit");

                    b.Property<long>("LatencyInChrome")
                        .HasColumnType("bigint");

                    b.Property<long>("LoadEventEnd")
                        .HasColumnType("bigint");

                    b.Property<long>("LoadEventInChrome")
                        .HasColumnType("bigint");

                    b.Property<long>("LoadEventStart")
                        .HasColumnType("bigint");

                    b.Property<long>("NavigationStart")
                        .HasColumnType("bigint");

                    b.Property<long>("RedirectEnd")
                        .HasColumnType("bigint");

                    b.Property<long>("RedirectStart")
                        .HasColumnType("bigint");

                    b.Property<long>("RequestStart")
                        .HasColumnType("bigint");

                    b.Property<long>("ResponseEnd")
                        .HasColumnType("bigint");

                    b.Property<long>("ResponseStart")
                        .HasColumnType("bigint");

                    b.Property<long>("SecureConnectionStart")
                        .HasColumnType("bigint");

                    b.Property<int>("SiteId")
                        .HasColumnType("int");

                    b.Property<string>("SourceIpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TimetakenToGenerateInMs")
                        .HasColumnType("bigint");

                    b.Property<long>("UnloadEventEnd")
                        .HasColumnType("bigint");

                    b.Property<long>("UnloadEventStart")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("Timings");
                });

            modelBuilder.Entity("PlaywrightTestLinuxContainer.Entities.TimingEntity", b =>
                {
                    b.HasOne("PlaywrightTestLinuxContainer.Entities.SiteEntity", "Site")
                        .WithMany("Timings")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("PlaywrightTestLinuxContainer.Entities.SiteEntity", b =>
                {
                    b.Navigation("Timings");
                });
#pragma warning restore 612, 618
        }
    }
}
